// GENERATED by build.mjs — do not edit. Real entry: lib/main.js.
let mod;
try {
  mod = await import('./main.js');
} catch (error) {
  console.error('[femo-plugin][entry-diag] main graph import failed:', error && (error.stack || error));
  throw error;
}
export const name = mod.name;
export const Config = mod.Config;
export const inject = mod.inject;
export const apply = mod.apply;
export default mod.default;
