/**
 * Build script: TS source -> deployable package.
 *
 * Two artifacts:
 *  - lib/client.js — browser bundle in ModuleLoader.load format (the web
 *    shell's client module loader; see @deepseek-ai/dsh-client-modules).
 *  - lib/index.js — host loader entry (exports["."] / main), loaded by the
 *    dsh Node process.
 */
import { build, context } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const watch = process.argv.includes('--watch');

// 构建前先做「漏 import」体检（2026-09-19）：本机没装 typescript、esbuild 又不会
// 对「用了但没 import 的标识符」报错（当全局自由变量原样输出，运行期才炸），所以
// 这类错必须自己兜住——实锤：subagent-native.ts 漏 import actorNameOf，构建静默
// 通过、节点一跑就 ReferenceError 整场挂起。体检不过直接退出，不产出坏包。
execFileSync(process.execPath, [fileURLToPath(new URL('./check-imports.mjs', import.meta.url))], { stdio: 'inherit' });

const nodePaths = [fileURLToPath(new URL('./node_modules', import.meta.url))];

const clientOptions = {
  entryPoints: ['./client/client.tsx'],
  bundle: true,
  platform: 'browser',
  format: 'cjs',
  // 必须显式 automatic：femoGen/src/faIcons.jsx（.jsx）不在本 tsconfig 的
  // react-jsx 覆盖范围内，默认 transform 会编出裸 React.createElement，
  // 运行时抛 "React is not defined"（2026-09-14 FaIcon 崩溃修复）。
  jsx: 'automatic',
  outfile: 'lib/client.js',
  // react 走 shell 单例（ModuleLoader 的 require 解析到 seed 里的 react），
  // 不能打进 bundle——否则双 React 实例会崩掉 slots 渲染。
  // ui-primitives 同理。2026-09-04：client-runtime 从 externals 移除——rc.1 删除
  // 该包，femo 的最后一位运行时消费者（lineage-fork 的 indexSubagentDescendants）
  // 已本地化，client bundle 对已删包零引用（type-only 导入构建期擦除）。
  external: [
    'react', 'react/jsx-runtime', 'react-dom', 'react-dom/client',
    '@deepseek-ai/dsh-client-ui-primitives',
  ],
  banner: {
    js: [
      'window.__ModuleLoader__.load({',
      '  id: "femo-plugin",',
      '  factory: (require) => {',
      '    var module = { exports: {} };',
      '    var exports = module.exports;',
    ].join('\n'),
  },
  footer: {
    js: ['    return module.exports;', '  }', '});'].join('\n'),
  },
  sourcemap: true,
  logLevel: 'info',
};

const hostOptions = {
  entryPoints: ['./host/index.ts'],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  nodePaths,
  outfile: 'lib/main.js',
  sourcemap: true,
  logLevel: 'info',
  // bundle 进来的 CJS 依赖（yaml@2 的 dist 里有 require('process') 这类内联
  // 内建require）在 ESM 输出里落到 esbuild 的抛错垫片上——运行时第一次
  // parse() 就炸。banner 在模块顶提供真 require（esbuild 官方推荐解法），
  // 垫片的 typeof require 分支随之走通。
  banner: {
    js: "import { createRequire as __femoCreateRequire } from 'node:module'; const require = __femoCreateRequire(import.meta.url);",
  },
  // dsh-session 2026-09-23 起改走宿主实例桥（host/dsh-session-host.ts，alias）：
  // 此前 external → 运行时拉自带私有 rc.2 副本，0.1.7 的进程内解析把副本的
  // dsh-llm 请求劫持到宿主新副本（CallId 等导出已挪走）→ 链接期 SyntaxError →
  // 整个插件 failed to import。桥用 createRequire(宿主入口) 直取宿主进程里的
  // 那份实例（与持久化协调器同源，正是本注释历史要求的共享实例语义），
  // 0.1.6/0.1.7 双版本一致。详见 host/dsh-session-host.ts 头注。
  alias: {
    '@deepseek-ai/dsh-session': './host/compat/dsh-session-host.ts',
  },
};

// 2026-09-23（0.1.7 兼容首战）：lib/index.js 改为生成的「诊断壳」，真身搬进
// lib/main.js。背景：dsh 0.1.7 的启动审计对「import 都没完成」的插件只报一句
// "failed to import"，真实异常被 cordis loader 的 logger.error 吞进对未激活
// 条目无处可去的通道——console 永远看不到堆栈。壳在 re-export 前先动态
// import 真身，失败即把完整堆栈打到 stderr 再原样抛出，宿主日志可见。
// 双版本无害：0.1.6 上 import 不失败，壳只是一层透传。
import { writeFileSync } from 'node:fs';

const ENTRY_SHELL = `// GENERATED by build.mjs — do not edit. Real entry: lib/main.js.
let mod;
try {
  mod = await import('./main.js');
} catch (error) {
  console.error('[femo-plugin][entry-diag] main graph import failed:', error && (error.stack || error));
  throw error;
}
export const name = mod.name;
export const Config = mod.Config;
export const inject = mod.inject;
export const apply = mod.apply;
export default mod.default;
`;

writeFileSync(new URL('./lib/index.js', import.meta.url), ENTRY_SHELL);

if (watch) {
  await (await context(clientOptions)).watch();
  await (await context(hostOptions)).watch();
  console.log('[build] watching dshAdapter/ for changes...');
} else {
  await Promise.all([build(clientOptions), build(hostOptions)]);
}
